plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.iesaguadulce.mirecetariodecocina'
    compileSdk = 35

    defaultConfig {
        applicationId = "com.iesaguadulce.mirecetariodecocina"
        minSdk = 28
        targetSdk = 35
        versionCode = 3
        versionName = "1.2"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding = true
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    // Librerías base en Java (eliminadas las -ktx innecesarias)
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'androidx.navigation:navigation-fragment:2.8.3'
    implementation 'androidx.navigation:navigation-ui:2.8.3'
    implementation 'androidx.room:room-runtime:2.6.1'
    annotationProcessor 'androidx.room:room-compiler:2.6.1'
    
    // Pruebas Unitarias (Local)
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.7.0'
    testImplementation 'androidx.test.ext:junit:1.2.1'
    testImplementation 'org.robolectric:robolectric:4.14.1'

    // Pruebas de Integración (Instrumented)
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    // Librería esencial para probar LiveData en Java
    androidTestImplementation 'androidx.arch.core:core-testing:2.2.0'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
